name: Unit Tests
on: push
jobs:
  jest-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm ci
        
      - name: Unit Test
        run: npm run test